name: visnagarbullion
description: A new Flutter project.

#environment:
#  sdk: ">=2.0.0-dev.68.0 <3.0.0"

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  fluttertoast: ^7.0.4

  intl: ^0.16.1

  shared_preferences: ^0.5.10

  http: ^0.12.0

  feature_discovery: ^0.13.0+2

  xml: ^4.1.0

  custom_progress_dialog: ^1.0.5

  flutter_cache_manager: ^2.1.1

  url_launcher: 5.5.0

  flutter_launch: ^0.2.0

  adhara_socket_io: ^0.4.2+1

  connectivity: ^2.0.2

  webview_flutter: ^0.3.14+1

  cached_network_image: ^2.5.0

  marquee: ^1.6.1

  flutter_local_notifications: ^0.7.1+1

  firebase_messaging: ^5.0.1+1

  draggable_widget: ^1.1.1

  device_info: ^1.0.0

  package_info: ^0.4.0+13

  store_redirect: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/logo.png
    - assets/images/logomain.png
    - assets/images/call.png
    - assets/images/liverate.svg
    - assets/images/update.svg
    - assets/images/bank.svg
    - assets/images/news.svg
    - assets/images/contact.svg
    - assets/images/ecocalendar.png
    - assets/images/markettrend.png
    - assets/images/logovisnagrsplsee.png
    - assets/images/whatsapp.png
    - assets/images/whatsappnew.png
    - assets/calender.html
  fonts:
    - family: RobotoRegular
      fonts:
        - asset: fonts/RobotoRegular.ttf